manifest = "539fe2c4bcc0603d6e5b376e03d4a93c7fe5f5124ed1d3454256c5649f076d4f"

[[dependency]]
package = "github.com/buckaroo-pm/host-pthread"
target = "//:pthread"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "76044bba206818f3378c346396f4a33de338d71c"
